### ISSUE TITLE
Select region upfront

### ISSUE THREAD

**Issue by KevCaz** [inSilecoInc/shinySpatialApp#10]
Include a section to select region when providing info about the user - this will
determine the customized info for the report (i.e. Maritimes Region, Gulf Region [semi-
empty RMD]).

**Comment by david-beauchesne** [comment]
@KevCaz est-ce qu'ils nous ont déjà indiqué ça sera quoi les différences à générer pour les rapports d'une région à l'autre? Et est-ce qu'il faut uniquement identifier la région du Golfe et des Maritimes?

**Comment by david-beauchesne** [comment]
Déterminer s'il faut forcer l'utilisateur de faire un choix, ou si les Maritimes par défaut ça fonctionne. Le code sera légèrement différent si on veut forcer l'utilisateur à faire un choix et laisser l'option par défaut vide. 

Voir https://stackoverflow.com/questions/24175997/force-no-default-selection-in-selectinput

**Comment by KevCaz** [comment]
Je sais pas a quelle point il faut forcer. Je pense qu'on peut y aller light et juste changer les choix que àa entraine.

**Comment by david-beauchesne** [comment]
En terme de code je crois que le plus light serait de mettre la version Maritime par défaut et d'ajuster si un utilisateur choisi la région du Golfe

**Comment by david-beauchesne** [comment]
Done with commit 8074ac294483d641da72fb94eb7c773114c458a0
