### ISSUE TITLE
Update visualization window

### ISSUE THREAD

**Issue by KevCaz** [inSilecoInc/shinySpatialApp#12]
Update the visualization window in the app so the user can see polygons/buffers that are
uploaded as shape files or bounding boxes.

**Comment by david-beauchesne** [comment]
@KevCaz ici est-ce qu'on parle des fichiers qui sont uploadé dans l'onglet `Import files` et des buffers qui peuvent être ajoutés?

**Comment by KevCaz** [comment]
oui, mais au final c'est un truc qui marchait déjà me semble...

**Comment by KevCaz** [comment]
enfin je croyais... à checker!

**Comment by david-beauchesne** [comment]
Now added as part of the validate tab in commit 326dd50e049017c828d77b3254cde2bf30af38e7, unless we did not understand the issue correctly. A user can now update the extent on the map based on the geoms selected
