### ISSUE TITLE
Zoom into selected area

### ISSUE THREAD

**Issue by KevCaz** [inSilecoInc/shinySpatialApp#14]
Explore the possibility for the map to zoom into the area selected (whether by point,
bounding box, polygon drawn on screen).

**Comment by KevCaz** [comment]
Use `osmdata` e.g. `q <- getbb("Iles de la Madeleine")` then use `q` (binding box) to determine zoom and loc.

**Comment by KevCaz** [comment]
https://github.com/r-spatial/mapedit/pull/100 Maybe some ideas for other features.

**Comment by david-beauchesne** [comment]
Now added as part of the validate tab in commit 326dd50e049017c828d77b3254cde2bf30af38e7
